server:
  port: 0

spring:
  mail:
    host: smtp.naver.com
    port: 587
    username: 1214alex@naver.com
    password: Tjdwns011214@
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
          ssl.trust: smtp.naver.com

  data:
    redis:
      host: localhost
      port: 6380

  application:
    name: dieat-user-service

  ## db config
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/samsung
    username: root
    password: mariadb

  ## jpa config
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
    properties:
      hibernate:
        '[format_sql]': true


token:
  expiration_time: 43200000
  secret: mc9guIbkofqAXON+dGiHxx30+27aW+oBDI+JTvWHzSxrkYSV6yfE/gpDoBXUt4N34h0W2jzU74PAaroIvRmpew==


#admin:
#  secret: ${admin.secret}
admin:
  secret: IrKAqF/iFu/dOWF3F525uC6pPU383WJCkQBcpdamX3bXXYliYr5fK2Gasr/Lby1iktgZ877VSKhBC7DgprPX6Q==

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    org.springframework.security: DEBUG
    com.samsung.dieat.member.security: DEBUG

